#!/usr/bin/env node
/**
 * Wrap the browser half into the shell's loader artifact.
 *
 * The shell fetches a client plugin as a classic script whose only contract is
 * `window.__ModuleLoader__.load({ id, factory })`, with `factory(require)`
 * resolving platform modules from the browser module table. `src/client/index.cjs`
 * is already authored against that `require`, so this step adds the wrapper
 * (and the `module`/`exports` pair the factory body writes through) and copies
 * it to `lib/client.js` — a bundler would have nothing left to bundle.
 *
 * Run by `npm run build`; `npm run build:client` alone refreshes the artifact
 * during client-only work.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const packageDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const manifest = JSON.parse(readFileSync(resolve(packageDir, 'package.json'), 'utf8'))
const source = resolve(packageDir, 'src', 'client', 'index.cjs')
const outfile = resolve(packageDir, 'lib', 'client.js')

const body = readFileSync(source, 'utf8').trimEnd()
const artifact = [
  '// Generated by scripts/build-client.mjs from src/client/index.cjs — do not edit.',
  `window.__ModuleLoader__.load({ id: ${JSON.stringify(manifest.name)}, factory: (require) => {`,
  'var module = { exports: {} }; var exports = module.exports;',
  body,
  'return module.exports; } });',
  '',
].join('\n')

mkdirSync(dirname(outfile), { recursive: true })
writeFileSync(outfile, artifact)
console.log(`build-client: wrote ${outfile}`)
